package com.example.expensetracker.repository;

import com.example.expensetracker.model.Budget;
import com.example.expensetracker.model.BudgetView;
import com.example.expensetracker.model.ExpenseView;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * BudgetRepository — CRUD operations for Budgets and budget-drill-down queries.
 *
 * Design overview:
 *   A Budget row stores a spending limit (limit_amount) for a specific user +
 *   category combination over a date range. The application never stores a
 *   "spent" column in the database; instead, findAllBudgetViews() uses a
 *   LEFT JOIN + SUM(e.amount) to calculate how much has been spent within
 *   each budget's date window at query time, keeping the data non-redundant
 *   (BCNF-compliant).
 *
 * Data isolation:
 *   Every method that returns or deletes budget data accepts an Integer userId.
 *     - null  → admin caller: no user filter, all budgets are visible/deletable.
 *     - value → regular user: WHERE/AND b.user_id = ? restricts the operation
 *               to only that user's budgets, enforced at the SQL layer.
 *
 * SQL injection prevention:
 *   All values are passed as parameterized ? placeholders via JdbcTemplate.
 *   User-supplied input is never concatenated into SQL strings.
 *
 * Exception handling:
 *   JdbcTemplate converts JDBC SQLExceptions into Spring's DataAccessException
 *   hierarchy. Each method catches DataAccessException and rethrows as
 *   RuntimeException with a descriptive message identifying the failing query.
 */
@Repository
public class BudgetRepository {

    // JdbcTemplate is injected by Spring and backed by HikariCP connection pooling.
    private final JdbcTemplate jdbcTemplate;

    public BudgetRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    // ── CREATE ────────────────────────────────────────────────────────────────

    /**
     * Inserts a new budget row for the logged-in user.
     *
     * The userId stored on the Budget object comes from the HTTP session (set at
     * login time), not from a form field. This means a regular user cannot craft
     * a request to create a budget under a different user_id.
     *
     * SQL:
     *   INSERT INTO Budgets (user_id, category_id, limit_amount, start_date, end_date)
     *   VALUES (?, ?, ?, ?, ?)
     *
     * @param budget a Budget record carrying userId, categoryId, limitAmount,
     *               startDate, and endDate (budgetId is null — auto-generated by MySQL)
     */
    public void addBudget(Budget budget) {
        // Static INSERT — all five columns are always provided, so no dynamic SQL needed.
        String sql = """
            INSERT INTO Budgets (user_id, category_id, limit_amount, start_date, end_date)
            VALUES (?, ?, ?, ?, ?)
        """;

        try {
            // jdbcTemplate.update() is used for INSERT, UPDATE, and DELETE.
            // Bind values map left-to-right to each ? placeholder.
            jdbcTemplate.update(
                    sql,
                    budget.userId(),      // FK → Users.user_id
                    budget.categoryId(),  // FK → Categories.category_id
                    budget.limitAmount(), // DECIMAL(10,2) spending cap
                    budget.startDate(),   // DATE: inclusive lower bound
                    budget.endDate()      // DATE: inclusive upper bound
            );
        } catch (DataAccessException e) {
            throw new RuntimeException("Database error while adding budget: " + e.getMessage(), e);
        }
    }

    // ── READ ──────────────────────────────────────────────────────────────────

    /**
     * Returns all budgets as display-ready views with live spending totals.
     *
     * Query design — why LEFT JOIN + SUM instead of a stored column:
     *   Storing a running "spent" total in the Budgets table would violate BCNF
     *   (spent is functionally determined by the matching Expense rows, not by
     *   budget_id alone). Instead, the query computes spent_amount at read time
     *   using a LEFT JOIN against Expenses filtered to the same user, category,
     *   and date window. COALESCE(SUM(...), 0) ensures budgets with no matching
     *   expenses return 0 instead of NULL.
     *
     * Row mapper post-processing:
     *   remainingAmount and status are derived in the Java row mapper rather than
     *   in SQL to keep the calculation readable and to use BigDecimal arithmetic.
     *
     * SQL:
     *   SELECT b.budget_id,
     *          u.name        AS user_name,
     *          c.category_name,
     *          b.limit_amount,
     *          b.start_date,
     *          b.end_date,
     *          COALESCE(SUM(e.amount), 0) AS spent_amount
     *   FROM Budgets b
     *   JOIN Users u        ON b.user_id     = u.user_id
     *   JOIN Categories c   ON b.category_id = c.category_id
     *   LEFT JOIN Expenses e ON e.user_id     = b.user_id
     *                       AND e.category_id = b.category_id
     *                       AND e.date BETWEEN b.start_date AND b.end_date
     *   [WHERE b.user_id = ?]   -- appended only for non-admin callers
     *   GROUP BY b.budget_id, u.name, c.category_name,
     *            b.limit_amount, b.start_date, b.end_date
     *   ORDER BY b.budget_id ASC
     *
     * @param userId null for admin (all budgets), or session userId (own budgets only)
     */
    public List<BudgetView> findAllBudgetViews(Integer userId) {
        // --- Step 1: Build the base SELECT with JOIN and LEFT JOIN ---
        // The base query is always executed; dynamic filtering is appended in Step 2.
        StringBuilder sql = new StringBuilder("""
            SELECT
                b.budget_id,
                u.name AS user_name,
                c.category_name,
                b.limit_amount,
                b.start_date,
                b.end_date,
                COALESCE(SUM(e.amount), 0) AS spent_amount
            FROM Budgets b
            JOIN Users u      ON b.user_id     = u.user_id
            JOIN Categories c ON b.category_id = c.category_id
            LEFT JOIN Expenses e
                ON  e.user_id     = b.user_id
                AND e.category_id = b.category_id
                AND e.date BETWEEN b.start_date AND b.end_date
            WHERE 1=1
        """);
        // WHERE 1=1 is a no-op predicate that lets every optional filter be
        // appended as "AND ..." without special-casing the first condition.

        List<Object> params = new ArrayList<>();

        // --- Step 2: Apply user-scope filter (skipped for admins) ---
        if (userId != null) {
            // Regular users see only their own budgets.
            sql.append(" AND b.user_id = ? ");
            params.add(userId);
        }

        // --- Step 3: Append GROUP BY and ORDER BY ---
        // GROUP BY is required because of the SUM(e.amount) aggregate.
        // All non-aggregated SELECT columns must appear in GROUP BY.
        sql.append("""
            GROUP BY
                b.budget_id,
                u.name,
                c.category_name,
                b.limit_amount,
                b.start_date,
                b.end_date
            ORDER BY b.budget_id ASC
        """);

        try {
            // --- Step 4: Execute and map each row to a BudgetView ---
            return jdbcTemplate.query(sql.toString(), (rs, rowNum) -> {

                // Retrieve raw amounts from the ResultSet.
                BigDecimal limitAmount = rs.getBigDecimal("limit_amount");
                BigDecimal spentAmount = rs.getBigDecimal("spent_amount");

                // Defensive null guards — COALESCE should prevent nulls,
                // but guard anyway in case of unexpected database state.
                if (limitAmount == null) limitAmount = BigDecimal.ZERO;
                if (spentAmount == null) spentAmount = BigDecimal.ZERO;

                // Derive remaining balance: positive = under budget, negative = over budget.
                BigDecimal remainingAmount = limitAmount.subtract(spentAmount);

                // Human-readable status label shown in the UI status column.
                String status = remainingAmount.compareTo(BigDecimal.ZERO) < 0
                        ? "Over Budget"
                        : "Within Budget";

                // Construct and return the immutable BudgetView record.
                return new BudgetView(
                        rs.getInt("budget_id"),
                        rs.getString("user_name"),
                        rs.getString("category_name"),
                        limitAmount,
                        rs.getDate("start_date").toLocalDate(),
                        rs.getDate("end_date").toLocalDate(),
                        spentAmount,
                        remainingAmount,
                        status
                );
            }, params.toArray());

        } catch (DataAccessException e) {
            throw new RuntimeException("Database error while fetching budgets: " + e.getMessage(), e);
        }
    }

    /**
     * Returns the individual expense rows that count toward a specific budget.
     *
     * Query design:
     *   The query starts from Budgets (filtered to a single row by budget_id),
     *   then JOINs Expenses on the three matching conditions: same user, same
     *   category, and date within the budget's date range. Users and Categories
     *   are joined for display names. This produces only expenses that directly
     *   contribute to the selected budget's spent total.
     *
     * Security:
     *   When userId is non-null, AND b.user_id = ? is appended. This prevents a
     *   regular user from viewing another user's budget expenses by guessing a
     *   budget_id in the URL, because the WHERE clause would return no rows if
     *   the budget belongs to a different user.
     *
     * SQL:
     *   SELECT e.expense_id,
     *          u.name        AS user_name,
     *          c.category_name,
     *          e.expense_name,
     *          e.amount,
     *          e.date,
     *          e.payment_method,
     *          e.notes
     *   FROM Expenses e
     *   JOIN Users u      ON e.user_id     = u.user_id
     *   JOIN Categories c ON e.category_id = c.category_id
     *   JOIN Budgets b    ON b.budget_id   = ?
     *                    AND e.user_id     = b.user_id
     *                    AND e.category_id = b.category_id
     *                    AND e.date BETWEEN b.start_date AND b.end_date
     *   [AND b.user_id = ?]   -- appended only for non-admin callers
     *   ORDER BY e.date ASC, e.expense_id ASC
     *
     * @param budgetId the primary key of the budget to drill into
     * @param userId   null for admin (no ownership guard), or session userId
     */
    public List<ExpenseView> findExpensesForBudget(Integer budgetId, Integer userId) {
        // --- Step 1: Base query joining Expenses → Users, Categories, and Budgets ---
        // The JOIN Budgets b ON b.budget_id = ? filters the Budgets table to the
        // single target row, then the additional ON conditions restrict Expenses
        // to only those that fall within that budget's user/category/date window.
        StringBuilder sql = new StringBuilder("""
            SELECT e.expense_id,
                   u.name AS user_name,
                   c.category_name,
                   e.expense_name,
                   e.amount,
                   e.date,
                   e.payment_method,
                   e.notes
            FROM Expenses e
            JOIN Users u      ON e.user_id    = u.user_id
            JOIN Categories c ON e.category_id = c.category_id
            JOIN Budgets b    ON b.budget_id   = ?
                             AND e.user_id     = b.user_id
                             AND e.category_id = b.category_id
                             AND e.date BETWEEN b.start_date AND b.end_date
            WHERE 1=1
        """);

        List<Object> params = new ArrayList<>();
        params.add(budgetId); // bound to the first ? in the JOIN ON clause

        // --- Step 2: Ownership guard for non-admin users ---
        if (userId != null) {
            // Ensures a regular user can only view expenses for their own budgets.
            sql.append(" AND b.user_id = ?");
            params.add(userId);
        }

        // --- Step 3: Sort chronologically so the detail panel reads like a ledger ---
        sql.append(" ORDER BY e.date ASC, e.expense_id ASC");

        try {
            // --- Step 4: Execute and map each row to an ExpenseView ---
            return jdbcTemplate.query(sql.toString(), (rs, rowNum) ->
                    new ExpenseView(
                            rs.getInt("expense_id"),
                            rs.getString("user_name"),
                            rs.getString("category_name"),
                            rs.getString("expense_name"),
                            rs.getBigDecimal("amount"),
                            rs.getDate("date").toLocalDate(),
                            rs.getString("payment_method"),
                            rs.getString("notes")
                    ), params.toArray()
            );
        } catch (DataAccessException e) {
            throw new RuntimeException(
                    "Database error while fetching expenses for budget #" + budgetId + ": " + e.getMessage(), e);
        }
    }

    // ── DELETE ────────────────────────────────────────────────────────────────

    /**
     * Deletes a budget by its primary key.
     *
     * Security: when userId is non-null, AND user_id = ? is appended to the
     * WHERE clause. This ensures a regular user can only delete their own budgets
     * even if they craft a request with a foreign budget_id — the extra predicate
     * simply matches zero rows and the DELETE is a no-op.
     *
     * SQL:
     *   DELETE FROM Budgets
     *   WHERE budget_id = ?
     *   [AND user_id = ?]   -- appended only for non-admin callers
     *
     * @param budgetId the primary key of the budget to remove
     * @param userId   null for admin (unconditional delete), or session userId
     */
    public void deleteBudget(Integer budgetId, Integer userId) {
        // --- Step 1: Start with the primary-key filter ---
        StringBuilder sql = new StringBuilder("DELETE FROM Budgets WHERE budget_id = ?");
        List<Object> params = new ArrayList<>();
        params.add(budgetId);

        // --- Step 2: Append ownership guard for non-admin callers ---
        if (userId != null) {
            sql.append(" AND user_id = ?");
            params.add(userId);
        }

        try {
            // jdbcTemplate.update() executes DML (INSERT / UPDATE / DELETE).
            // Returns the number of rows affected; we don't need it here.
            jdbcTemplate.update(sql.toString(), params.toArray());

        } catch (DataAccessException e) {
            throw new RuntimeException(
                    "Database error while deleting budget #" + budgetId + ": " + e.getMessage(), e);
        }
    }
}
